// main_muti_motor.cpp
// Function:
// 1. Receive commands from serial port
// 2. Control multiple stepper motors with acceleration and deceleration

// Maintanance:
// 1. Only activate one motor at a time.
// 2. The distance and the speed will be determined by the number of steps and the time interval.

#include "main.h" // Motor parameters here
#include <math.h>
#include <Arduino.h>

Motor motors[] = {
    {11, 10, 99},    // Motor 0 {step, dir}
    {13, 12, 99},    // Motor 1 {step, dir}
    {6, 7, 9},      // Motor 2 {step, dir}
    {4, 5, 8}       // Motor 3 {step, dir}
};

char lineBuf[LINE_BUF_SIZE];
int lineIndex = 0;
SystemState systemState = SystemState::IDLE;

AxisMoveCommand currentMove_A; // Only use this parameter in startMotion_A()
AxisMotionRuntime Motion_A;     // Only use this parameter in update_S_Motion()

DualMoveCommand currentMove_D;   // Only use this parameter in start_d_Motion()
DualMotionRuntime Motion_D;       // Only use this parameter in update_d_Motion()

void handleMoveCommand_A(char *cmd);
void startMotion_A();
void handleMoveCommand_D(char *cmd);
void startMotion_D();

//==================================================
// SYSTEM FUNCTIONS
//==================================================

void AxisPulse(Motor &motor, unsigned long highPulseUS = 10){
    digitalWrite(motor.stepPin, HIGH);
    delayMicroseconds(highPulseUS); // Drv8825 requires a minimum pulse width of 1.9us, so we use 3us to be safe
    digitalWrite(motor.stepPin, LOW);
}

bool getNextToken(char *&token) {
    token = strtok(NULL, " ");
    if (token == NULL) {
        Serial.println("[ERROR] Command Format Error...");
        return false;
    }
    return true;
}

void initMotion(AxisMotionRuntime &motion, const AxisMoveCommand &currentMove)
{
    motion.stepTicks = currentMove.stepNUM;
    motion.rampTicks = currentMove.rampTicks;
    motion.ticksIndex = 0;
    motion.targetDelayUS = currentMove.stepDelayUS;

    // If ramp is not specified
    if (motion.rampTicks < 1) 
        motion.rampTicks = motion.stepTicks / 4;

    motion.deltaDelayUS = (START_DELAY_US - motion.targetDelayUS) / motion.rampTicks;

    motion.currentDelayUS = START_DELAY_US;
    motion.lastStepUS = micros();

    Motor &targetMotor = motors[currentMove.motorIdx];
    digitalWrite(targetMotor.dirPin, currentMove.dir == Direction::POSITIVE);

    if (targetMotor.enaPin != 99)
        digitalWrite(targetMotor.enaPin, LOW);
}

const char* getSystemStateName(SystemState state)
{
    switch (state)
    {
        case SystemState::IDLE:     return "IDLE";
        case SystemState::S_RUNNING:  return "SINGLE_RUNNING";
        case SystemState::D_RUNNING:    return "DUAL_RUNNING";
        case SystemState::ERROR:    return "ERROR";
        default:                    return "UNKNOWN";
    }
}

void handleCommand(char *cmd) {
    // Handle the *lineBuf* received from updateSerial() and execute the corresponding command.
    if (strlen(cmd) == 0)
        return;

    if (strcmp(cmd, "PING") == 0) {
        Serial.println("PONG");
    }

    else if (strcmp(cmd, "STATUS") == 0) {
        Serial.println(getSystemStateName(systemState));
    }

    else if (strcmp(cmd, "STOP") == 0) {
        if (systemState == SystemState::S_RUNNING) {
            if (motors[currentMove_A.motorIdx].enaPin != 99) { // make a stop function
                digitalWrite(motors[currentMove_A.motorIdx].enaPin, HIGH);
            }
            systemState = SystemState::IDLE;
            Serial.println("[OK] Stopping the motor...");
        } 
        else if (systemState == SystemState::D_RUNNING) {
            // Disable Motor A
            if (motors[currentMove_D.motorA.motorIdx].enaPin != 99)
                digitalWrite(motors[currentMove_D.motorA.motorIdx].enaPin, HIGH);

            // Disable Motor B
            if (motors[currentMove_D.motorB.motorIdx].enaPin != 99)
                digitalWrite(motors[currentMove_D.motorB.motorIdx].enaPin, HIGH);

            systemState = SystemState::IDLE;
            Serial.println("[OK] Stopping the motor...");
        }
        else {
            Serial.println("[Error] Not Running Now...");
        }
    }

    else if (strcmp(cmd, "GET_CONFIG") == 0){
        Serial.println("[OK] Returning the Configs...");
        Serial.print("CONFIG motors_number=");
        Serial.print(MOTOR_COUNT);

        Serial.print(" start_delau_us=");
        Serial.print(START_DELAY_US);

        Serial.print(" max_delau_us=");
        Serial.println(MAX_DELAY_US);
    }

    else if (strncmp(cmd, "S_MOVE", 4) == 0) {
        if (systemState != SystemState::IDLE) {
            Serial.println("[Error] System is Busy Now...");
            return;
        }
        handleMoveCommand_A(cmd);
    }
    else if (strncmp(cmd, "D_MOVE", 4) == 0) {
        if (systemState != SystemState::IDLE) {
            Serial.println("[Error] System is Busy Now...");
            return;
        }
        handleMoveCommand_D(cmd);
    }
    else {
        Serial.println("[Error] Unknown Command...");
    }
}

//==================================================
// AXIS MOTION
// =================================================

void handleMoveCommand_A(char *cmd) {
    char *token;
    token = strtok(cmd, " ");   // MOVE
    // Motor
    if (!getNextToken(token)) return;
    currentMove_A.motorIdx = atoi(token);
    if (currentMove_A.motorIdx < 0 || currentMove_A.motorIdx >= MOTOR_COUNT) {
        Serial.println("ERROR Invalid Motor...");
        return;
    }

    // Direction
    if (!getNextToken(token)) return;
    int dir = atoi(token);
    if (dir == 0) {
        currentMove_A.dir = Direction::NEGATIVE;
    }
    else if (dir == 1) {
        currentMove_A.dir = Direction::POSITIVE;
    }
    else {
        Serial.println("[ERROR] Direction Must Be 0 or 1...");
        return;
    }

    // Steps
    if (!getNextToken(token)) return;
    currentMove_A.stepNUM = atoi(token);

    // Step Delay
    if (!getNextToken(token)) return;
    currentMove_A.stepDelayUS = atoi(token);

    // Ramp
    if (!getNextToken(token)) return;
    currentMove_A.rampTicks = atoi(token);

    // Finish handling the move command 
    startMotion_A();
    Serial.print("[OK] Motor ");
    Serial.print(currentMove_A.motorIdx);
    Serial.println(" is Running...");
    Serial.print("Speed: ");
    Serial.println(currentMove_A.stepDelayUS);
}

void startMotion_A() {
    initMotion(Motion_A, currentMove_A);
    systemState = SystemState::S_RUNNING;
}

//==================================================
// DUAL MOTION
//==================================================

void handleMoveCommand_D(char *cmd) {
    char *token;
    token = strtok(cmd, " "); // D_MOVE

    // MOTOR A
    if (!getNextToken(token)) return;
    currentMove_D.motorA.motorIdx = atoi(token); // index of motor A
    if ( currentMove_D.motorA.motorIdx < 0 || currentMove_D.motorA.motorIdx >= MOTOR_COUNT) {
        Serial.println("[ERROR] Invalid Motor A...");
        return;
    }

    if (!getNextToken(token)) return;
    int dir = atoi(token); // direction of motor A
    if (dir == 0) {
        currentMove_D.motorA.dir = Direction::NEGATIVE;
    }
    else if (dir == 1) {
        currentMove_D.motorA.dir = Direction::POSITIVE;
    }
    else {
        Serial.println("[ERROR] Direction Must Be 0 or 1...");
        return;
    }

    if (!getNextToken(token)) return;
    currentMove_D.motorA.stepNUM = atol(token); // number of steps for motor A

    if (!getNextToken(token)) return;
    currentMove_D.motorA.stepDelayUS = atol(token); // step delay for motor A

    // MOTOR B
    if (!getNextToken(token)) return;
    currentMove_D.motorB.motorIdx = atoi(token); // index of motor B
    if ( currentMove_D.motorB.motorIdx < 0 || currentMove_D.motorB.motorIdx >= MOTOR_COUNT ) {
        Serial.println("[ERROR] Invalid Motor B...");
        return;
    }

    if (!getNextToken(token)) return;
    int dir = atoi(token); // direction of motor B
    if (dir == 0) {
        currentMove_D.motorB.dir = Direction::NEGATIVE;
    }
    else if (dir == 1) {
        currentMove_D.motorB.dir = Direction::POSITIVE;
    }
    else {
        Serial.println("[ERROR] Direction Must Be 0 or 1...");
        return;
    }

    if (!getNextToken(token)) return;
    currentMove_D.motorB.stepNUM = atol(token); // number of steps for motor B

    if (!getNextToken(token)) return;
    currentMove_D.motorB.stepDelayUS = atol(token); // step delay for motor B

    // CHECKING PARAMETERS
    if (currentMove_D.motorA.motorIdx == currentMove_D.motorB.motorIdx) {
        Serial.println("[ERROR] Motor A and Motor B Cannot Be The Same...");
        return;
    }

    if ( currentMove_D.motorA.stepNUM == 0 && currentMove_D.motorB.stepNUM == 0 ) {
        Serial.println("[ERROR] Both Steps Cannot Be Zero...");
        return;
    }

    // Start Dual Motion
    startMotion_D();
    Serial.println("[OK] Dual Motion Started...");
    Serial.print("Motor A: ");
    Serial.print(currentMove_D.motorA.motorIdx);
    Serial.print("Motor B: ");
    Serial.print(currentMove_D.motorB.motorIdx);
}

void startMotion_D() {
    initMotion(Motion_D.motorA, currentMove_D.motorA);
    initMotion(Motion_D.motorB, currentMove_D.motorB);
    Motion_D.pointStatus = PointStatus::FULL_RANGE; // Default to full range motion (include acceleration and deceleration)
    systemState = SystemState::D_RUNNING;
}

//==================================================
// UPDATE FUNCTIONS
//==================================================

void updateSerial() { 
    // Read serial input and package it into *lineBuf*
    while (Serial.available() > 0) {
        char c = Serial.read();
        if (c == '\n' || c == '\r') {
            lineBuf[lineIndex] = '\0';
            if (lineIndex > 0) {
                handleCommand(lineBuf);
            }
            lineIndex = 0;
        }
        else {
            if (lineIndex < LINE_BUF_SIZE - 1) {
                lineBuf[lineIndex++] = c;
            }
        }
    }
}

void updateMotion_A() {
    if (systemState != SystemState::S_RUNNING)
        return;

    unsigned long now = micros();
    if (now - Motion_A.lastStepUS < Motion_A.currentDelayUS) // unit not the same
        return;
    Motion_A.lastStepUS = now;
    AxisPulse(motors[currentMove_A.motorIdx]);
    Motion_A.ticksIndex++;

    // Acceleration
    if (Motion_A.ticksIndex < Motion_A.rampTicks) {
        if (Motion_A.currentDelayUS > MIN_DELAY_US + Motion_A.deltaDelayUS) // Make sure the current delay is greater than the minimum delay plus the delta delay
            Motion_A.currentDelayUS -= Motion_A.deltaDelayUS;
        else
            Motion_A.currentDelayUS = MIN_DELAY_US;
    }

    // Deceleration
    else if (Motion_A.ticksIndex >= Motion_A.stepTicks - Motion_A.rampTicks) {
        Motion_A.currentDelayUS += Motion_A.deltaDelayUS;

        if (Motion_A.currentDelayUS > START_DELAY_US)
            Motion_A.currentDelayUS = START_DELAY_US;
    }

    // Constant Speed
    else {
        Motion_A.currentDelayUS = MIN_DELAY_US;
    }

    // Finished
    if (Motion_A.ticksIndex >= Motion_A.stepTicks) {
        systemState = SystemState::IDLE;
        if (motors[currentMove_A.motorIdx].enaPin != 99) { // make a stop function
            digitalWrite(motors[currentMove_A.motorIdx].enaPin, HIGH);
        }
        Serial.println("DONE");
    }
}

void updateMotion_D() {
    if (systemState != SystemState::D_RUNNING)
        return;

    unsigned long now = micros();

    // Motor A
    if (Motion_D.motorA.ticksIndex < Motion_D.motorA.stepTicks) {
        if (now - Motion_D.motorA.lastStepUS >= Motion_D.motorA.currentDelayUS) {
            Motion_D.motorA.lastStepUS = now;
            Motion_D.motorA.ticksIndex++;
            AxisPulse(motors[currentMove_D.motorA.motorIdx]);

            if (Motion_D.pointStatus == PointStatus::ACCELERATING || Motion_D.pointStatus == PointStatus::FULL_RANGE) {
                // Acceleration
                if (Motion_D.motorA.ticksIndex < Motion_D.motorA.rampTicks) {
                    if (Motion_D.motorA.currentDelayUS > Motion_D.motorA.targetDelayUS + Motion_D.motorA.deltaDelayUS) {
                        Motion_D.motorA.currentDelayUS -= Motion_D.motorA.deltaDelayUS;
                    }
                    else {
                        Motion_D.motorA.currentDelayUS = Motion_D.motorA.targetDelayUS;
                    }
                }
            }
            else if (Motion_D.pointStatus == PointStatus::DECELERATING || Motion_D.pointStatus == PointStatus::FULL_RANGE) {
                // Deceleration
                if (Motion_D.motorA.ticksIndex >= Motion_D.motorA.stepTicks - Motion_D.motorA.rampTicks) {
                    Motion_D.motorA.currentDelayUS += Motion_D.motorA.deltaDelayUS;
                    if (Motion_D.motorA.currentDelayUS > START_DELAY_US)
                        Motion_D.motorA.currentDelayUS = START_DELAY_US;
                }
            }
            else {
                // Constant Speed
                Motion_D.motorA.currentDelayUS = Motion_D.motorA.targetDelayUS;
            }
        }
    }

    // Motor B
    if (Motion_D.motorB.ticksIndex < Motion_D.motorB.stepTicks) {
        if (now - Motion_D.motorB.lastStepUS >= Motion_D.motorB.currentDelayUS) {
            Motion_D.motorB.lastStepUS = now;
            Motion_D.motorB.ticksIndex++;
            AxisPulse(motors[currentMove_D.motorB.motorIdx]);
            // Acceleration
            if (Motion_D.motorB.ticksIndex < Motion_D.motorB.rampTicks) {
                if (Motion_D.motorB.currentDelayUS > Motion_D.motorB.targetDelayUS + Motion_D.motorB.deltaDelayUS) {
                    Motion_D.motorB.currentDelayUS -= Motion_D.motorB.deltaDelayUS;
                }
                else {
                    Motion_D.motorB.currentDelayUS = Motion_D.motorB.targetDelayUS;
                }
            }
            // Deceleration
            else if (Motion_D.motorB.ticksIndex >= Motion_D.motorB.stepTicks - Motion_D.motorB.rampTicks) {
                Motion_D.motorB.currentDelayUS += Motion_D.motorB.deltaDelayUS;
                if (Motion_D.motorB.currentDelayUS > START_DELAY_US)
                    Motion_D.motorB.currentDelayUS = START_DELAY_US;
            }
            // Constant Speed
            else {
                Motion_D.motorB.currentDelayUS = Motion_D.motorB.targetDelayUS;
            }
        }
    }

    // Finished
    if (Motion_D.motorA.ticksIndex >= Motion_D.motorA.stepTicks && Motion_D.motorB.ticksIndex >= Motion_D.motorB.stepTicks) {
        systemState = SystemState::IDLE;
        if (motors[currentMove_D.motorA.motorIdx].enaPin != 99)
            digitalWrite(motors[currentMove_D.motorA.motorIdx].enaPin, HIGH);

        if (motors[currentMove_D.motorB.motorIdx].enaPin != 99)
            digitalWrite(motors[currentMove_D.motorB.motorIdx].enaPin, HIGH);

        Serial.println("DONE");
    }
}

// =================================================
// ARDUINO MAIN LOOP
// =================================================

void setup() {
    // 初始化所有馬達
    for (int i = 0; i < MOTOR_COUNT; i++) {
        pinMode(motors[i].stepPin, OUTPUT);
        pinMode(motors[i].dirPin, OUTPUT);
        digitalWrite(motors[i].stepPin, LOW);
        digitalWrite(motors[i].dirPin, LOW);
        if (motors[i].enaPin != 99) {
            pinMode(motors[i].enaPin, OUTPUT);
            digitalWrite(motors[i].enaPin, HIGH);
        }
    }
    Serial.begin(115200);
    delay(500);
    Serial.println("READY");
}

void loop() {
    updateSerial();
    updateMotion_A();
    updateMotion_D();
}